name: Publish Meowsic Dependencies

on:
  workflow_dispatch:

jobs:
  build-meowsic-dependencies:
    name: Build Meowsic Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install required tools
        run: sudo apt-get update && sudo apt-get install -y unzip xz-utils zip

      - name: Download FFmpeg (Windows)
        run: |
          wget -O ff-win.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
          unzip -j ff-win.zip "*/bin/ffmpeg.exe" "*/bin/ffprobe.exe" -d ff-win

      - name: Download FFmpeg (Linux)
        run: |
          wget -O ff-linux.tar.xz https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
          mkdir ff-linux
          tar -xJf ff-linux.tar.xz --strip-components=1 --wildcards "*/ffmpeg" "*/ffprobe" -C ff-linux

      - name: Download yt-dlp binaries
        run: |
          wget -O yt-dlp-win64.exe https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe
          wget -O yt-dlp-linux64 https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux
          chmod +x yt-dlp-linux64

      - name: Package FFmpeg (Windows)
        run: |
          cd ff-win
          zip ../ffmpeg-win64.zip ffmpeg.exe ffprobe.exe

      - name: Package FFmpeg (Linux)
        run: |
          cd ff-linux
          zip ../ffmpeg-linux64.zip ffmpeg ffprobe

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "meowsic-deps-${{ github.run_id }}"
          name: "Meowsic Dependencies (${{ github.run_id }})"

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_release.outputs.tag_name }}
          files: |
            ffmpeg-win64.zip
            ffmpeg-linux64.zip
            yt-dlp-win64.exe
            yt-dlp-linux64
