name: Publish Meowsic Dependencies

on:
  workflow_dispatch:

jobs:
  publish-deps:
    name: Build and Publish (win64 + linux64)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RELEASE_TAG: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y wget unzip xz-utils zip

      - name: Download FFmpeg binaries
        run: |
          wget -O ff-win.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
          wget -O ff-linux.tar.xz https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz

      - name: Extract Win FFmpeg and GPL license
        run: |
          unzip -j ff-win.zip "*/bin/ffmpeg.exe" "*/LICENSE.txt" -d win64          
          mv win64/LICENSE.txt LICENSE-ffmpeg-gpl

      - name: Extract Linux FFmpeg
        run: |
          mkdir linux64
          tar -xJf ff-linux.tar.xz --strip-components=2 -C linux64 ffmpeg-master-latest-linux64-gpl/bin/ffmpeg
          chmod +x linux64/ffmpeg

      - name: Download yt-dlp binaries
        run: |
          wget -O win64/yt-dlp.exe https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe
          wget -O linux64/yt-dlp https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux
          chmod +x linux64/yt-dlp

      - name: Download FFmpeg-Builds' MIT license and yt-dlp's Unlicense
        run: |
          wget -O LICENSE-yt-dlp https://raw.githubusercontent.com/yt-dlp/yt-dlp/master/LICENSE
          wget -O LICENSE-ffmpeg-builds https://raw.githubusercontent.com/BtbN/FFmpeg-Builds/master/LICENSE

      - name: Package win64 ZIP
        run: |
          cd win64
          zip -j ../win64.zip yt-dlp.exe ffmpeg.exe ../LICENSE-yt-dlp ../LICENSE-ffmpeg-gpl ../LICENSE-ffmpeg-builds

      - name: Package linux64 ZIP
        run: |
          cd linux64
          zip -j ../linux64.zip yt-dlp ffmpeg ../LICENSE-yt-dlp ../LICENSE-ffmpeg-gpl ../LICENSE-ffmpeg-builds

      - name: List resulting ZIPs
        run: ls -lh win64.zip linux64.zip

      - name: Reset 'latest' tag if exists
        run: |
          git fetch --tags
          if git tag -l | grep -qx "${{ env.RELEASE_TAG }}"; then
            git push origin :refs/tags/${{ env.RELEASE_TAG }}
          fi

      - name: Push 'latest' tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f ${{ env.RELEASE_TAG }}
          git push origin ${{ env.RELEASE_TAG }} --force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: 'Meowsic Dependencies (latest)'
          tag_name: ${{ env.RELEASE_TAG }}
          body: |
            This release includes two OS-specific bundles:

            ❇️ **win64.zip**
             - `yt-dlp.exe` (executable)
             - `ffmpeg.exe` (executable)
             - `LICENSE-yt-dlp` (Unlicense — public domain)
             - `LICENSE-ffmpeg-gpl` (upstream GPL)
             - `LICENSE-ffmpeg-builds` (MIT license from BtbN project)

            ❇️ **linux64.zip**
             - `yt-dlp` (executable)
             - `ffmpeg` (executable)
             - `LICENSE-yt-dlp` (Unlicense — public domain)
             - `LICENSE-ffmpeg-gpl` (upstream GPL)
             - `LICENSE-ffmpeg-builds` (MIT license from BtbN project)

            No other binaries or source code are bundled.
          files: |
            ./win64.zip
            ./linux64.zip
