name: Publish Meowsic Dependencies

on:
  workflow_dispatch:

jobs:
  build-and-publish-dependencies:
    name: Build and Publish (win64 + linux64)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RELEASE_TAG: latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y wget unzip xz-utils zip

      - name: Download FFmpeg (Windows and Linux)
        run: |
          wget -O ff-win.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
          wget -O ff-linux.tar.xz https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz

      - name: Extract Windows FFmpeg and GPL license
        run: |
          unzip -j ff-win.zip "*/bin/ffmpeg.exe" "*/LICENSE.txt" -d win64
          mv win64/LICENSE.txt LICENSE-ffmpeg-gpl

      - name: Extract Linux FFmpeg
        run: |
          mkdir linux64
          tar -xJf ff-linux.tar.xz --strip-components=2 -C linux64 ffmpeg-master-latest-linux64-gpl/bin/ffmpeg
          chmod +x linux64/ffmpeg

      - name: Download yt-dlp binaries
        run: |
          wget -O win64/yt-dlp.exe https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe
          wget -O linux64/yt-dlp https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux
          chmod +x linux64/yt-dlp

      - name: Download yt-dlp Unlicense and BtbN MIT license
        run: |
          wget -O LICENSE-yt-dlp https://raw.githubusercontent.com/yt-dlp/yt-dlp/master/LICENSE
          wget -O LICENSE-ffmpeg-builds https://raw.githubusercontent.com/BtbN/FFmpeg-Builds/master/LICENSE

      - name: Add written source-offer (GPL §6)
        run: |
          echo "FFmpeg binary is built with GPL-enabled codecs as distributed by BtbN/FFmpeg-Builds." > FFmpeg-source-offer
          echo "Source code for this exact build is available here:" >> FFmpeg-source-offer
          echo "  https://github.com/BtbN/FFmpeg-Builds/releases/latest" >> FFmpeg-source-offer

      - name: Package win64.zip
        run: |
          cd win64
          zip -j ../win64.zip yt-dlp.exe ffmpeg.exe ../LICENSE-yt-dlp ../LICENSE-ffmpeg-gpl ../LICENSE-ffmpeg-builds ../FFmpeg-source-offer

      - name: Package linux64.zip
        run: |
          cd linux64
          zip -j ../linux64.zip yt-dlp ffmpeg ../LICENSE-yt-dlp ../LICENSE-ffmpeg-gpl ../LICENSE-ffmpeg-builds ../FFmpeg-source-offer

      - name: List files
        run: ls -lah

      - name: Reset 'latest' tag if exists
        run: |
          git fetch --tags
          if git tag -l | grep -qx "${{ env.RELEASE_TAG }}"; then
            git push origin :refs/tags/${{ env.RELEASE_TAG }}
          fi

      - name: Push 'latest' tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f ${{ env.RELEASE_TAG }}
          git push origin ${{ env.RELEASE_TAG }} --force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: 'Meowsic Dependencies (latest)'
          tag_name: ${{ env.RELEASE_TAG }}
          body: |
            ❇️ **win64.zip**
            - yt-dlp.exe (Unlicense)
            - ffmpeg.exe (GPL-enabled binary from BtbN/FFmpeg-Builds)
            - Includes:
              - LICENSE-yt-dlp (Unlicense)
              - LICENSE-ffmpeg-gpl (GPL license)
              - LICENSE-ffmpeg-builds (MIT wrapper license)
              - FFmpeg-source-offer (GPL source offer)

            ❇️ **linux64.zip**
            - yt-dlp (Unlicense)
            - ffmpeg (GPL-enabled binary)
            - Same set of license/source-offer files

            No other binaries or source code are bundled. All third-party code is from upstream and redistributed under its own license.
          files: |
            ./win64.zip
            ./linux64.zip
